run:
  skip-dirs:
    - (^|/)bin($|/)
    - (^|/)tmp($|/)
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - gofumpt
linters-settings:
  lll:
    line-length: 193
    tab-width: 1
  funlen:
    lines: 168
    statements: 50
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  golint:
    min-confidence: 0.6
  gosimple:
    checks: ["all","-S1023"]
  gofumpt:
    module-path: smolgit
    lang-version: "1.22.4"
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive
        - gosec
    - path: _mock.go
      linters:
        - funlen
        - maligned
        - noctx
        - scopelint
        - bodyclose
        - lll
        - goconst
        - gocognit
        - gocyclo
        - gochecknoinits
        - dupl
        - staticcheck
        - revive